site_name: Audiotools

repo_url: https://LyticaMx.github.io/voiceutils-audioTools/tree/v0.1.0
repo_name: voiceutils-audioTools@v0.1.0

theme:
   name: 'material'
   logo: 'https://cdn.discordapp.com/attachments/922938993987969054/1001964834151215154/Logo_M.png'
   favicon: 'https://cdn.discordapp.com/attachments/922938993987969054/1001964834151215154/Logo_M.png'
   palette:
      scheme: default
      primary: blue grey

plugins:
   - search
   - autorefs
   - mkdocstrings
   - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

nav:
   - Inicio: 'index.md'
   - "Documento de diseño": 'design_doc.md'
   - Ejemplos: 'examples.md'
   - Memoria: 'profiler.md'
   - 'API reference':
      - 'Decorators': 'api_reference/decorators.md'
      - 'Schemas': 'api_reference/schemas.md'
      - 'Types': 'api_reference/types.md'
      - 'Processing tools':
         - 'Audio processing': 'api_reference/processing_tools/audio_processing.md'
         - 'Feature extraction': 'api_reference/processing_tools/feature_extraction.md'
         - 'Pre-processing': 'api_reference/processing_tools/pre_processing.md'
      - 'Segmentation tools':
         - 'Feature segmentation': 'api_reference/segmentation_tools/feature_segmentation.md'
         - 'Label segmentation': 'api_reference/segmentation_tools/label_segmentation.md'
         - 'Sound Activity Detection': 'api_reference/segmentation_tools/sound_activity_detection.md'

extra:
   version:
      provider: mike
   social:
      - icon: fontawesome/brands/github
        link: https://github.com/LyticaMx

extra_css:
   - css/extra.css

markdown_extensions:
   - abbr
   - admonition
   - attr_list
   - def_list
   - footnotes
   - meta
   - toc:
       permalink: true
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.betterem:
       smart_enable: all
   - pymdownx.caret
   - pymdownx.critic
   - pymdownx.details
   - pymdownx.highlight
   - pymdownx.inlinehilite
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.snippets:
       check_paths: true
   - pymdownx.superfences:
       custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tabbed
   - pymdownx.tilde
   - pymdownx.tasklist:
        clickable_checkbox: true
        custom_checkbox: false
